spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./db/store
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none